### ISSUE TITLE
Category art not showing up

### ISSUE THREAD

**Issue by Emreler1** [webrcade/webrcade-docs#3]
Hi. There may be an issue about category art not showing up in the play mode but being present in the editor mode.

**Comment by raz0red** [comment]
Hmmm.. can you send me the feed to check out?

Thanks!

**Comment by Emreler1** [comment]
Hi Chris,

Please see the link of the json file from my Dropbox account.

https://tiny.cc/emreler1 <https://tiny.cc/emreler1>


Best,
Emre

**Comment by raz0red** [comment]
Hi-
I tried it, and everything seems to look correct, what is supposed to be broken?

Thanks, 
Chris

**Comment by raz0red** [comment]
Some of your categories are not appearing in the player because they don’t contain any items. Is that what you are referring to?

**Comment by Emreler1** [comment]
Sorry I wasn’t clear enough. The issue is that most of the artwork I linked does not seem to be working. Please see the screenshot attached. Only Atar 7800 and Game Boy have thumbnails showing up. But I linked all the platforms’ thumbnails. Sometimes none of them show up, sometimes just a few.

**Comment by Emreler1** [comment]
Nope. Even the ones that I added roms to are not showing up with a thumbnail. That’s what I meant.

**Comment by raz0red** [comment]
Unfortunately, I can't see the screenshot.

But, when I view your feed, all of the thumbnails are always showing
up.Very odd. Are you using a VPN or any other type of network filter?

Thanks,
Chris

**Comment by bkavuncu** [comment]
I experienced the same issue on old ipad, animations on slider causes the issue, removing it solves it. I think it is webkit version issue

`if (sliderHidden) {
      sliderStyle = {
        transform: 'translateY(150%)',
        opacity: 0
      }
    } else {
      sliderStyle = {
        transform: 'translateY(0%)',
        transition: '.8s ease-in-out', <-- this 
        animation: 'fadein .3s',  <--- and this lines
        opacity: 1
      }`

**Comment by Emreler1** [comment]
> I experienced the same issue on old ipad, animations on slider causes the issue, removing it solves it. I think it is webkit version issue
> 
> `if (sliderHidden) { sliderStyle = { transform: 'translateY(150%)', opacity: 0 } } else { sliderStyle = { transform: 'translateY(0%)', transition: '.8s ease-in-out', <-- this animation: 'fadein .3s', <--- and this lines opacity: 1 }`
> 
> Ofcourse this removes animation on the slider

My issue is gone after I switched from dropbox links for the image files to imgur links. But I always got the impression that when WebRcade is loading the feed it does not tolerate any latency. Anyway, how did you remove the slider animations?

**Comment by bkavuncu** [comment]
If you are using webrcade locally, you have to rebuild with these two lines commented out
`transition: '.8s ease-in-out', animation: 'fadein .3s'`
in slider component: src/react/components/slider/index.js

**Comment by Emreler1** [comment]
> If you are using webrcade locally, you have to rebuild with these two lines commented out
> `transition: '.8s ease-in-out', animation: 'fadein .3s'`
> in slider component: src/react/components/slider/index.js

I am completely lost at this. I have no idea how to change any code. I have no coder bone in me :) Thanks any way.
